data:
  dataset_path: "../marketdata"
#  dataset_path: "../non_standard_eurgbp"
  marketdata: "EURGBP_5M_2010-01-04_2025-05-29_MetaQuotes-Demo.csv"
#  marketdata: "EURUSD_20M_2010-01-04_2025-05-01_MetaQuotes-Demo.csv"
  start_date: "2025-01-04"
  end_date: "2025-05-28"

strategy:
#  donchian_window: 20             # Окно для канала Дончиана
#  rsi_period: 14                  # Период RSI
#  rsi_exit: 10                    # Порог RSI для выхода в кэш
#  cooldown_bars: 12               # Количество баров между сделками
  donchian_window: 11             # Окно для канала Дончиана
  rsi_period: 18                  # Период RSI
  rsi_exit: 42                    # Порог RSI для выхода в кэш
  cooldown_bars: 8               # Количество баров между сделками

  atr_enabled: true              # ATR включен
  atr_period: 20                  # Период ATR
  atr_threshold: 0.0001           # Порог для низкой волатильности ATR

  eod_exit: false                 # Выход в кэш по времени (учет торговой сессии)
  trading_hours:                  # Время, когда разрешено открытие сделок (включительно)
    allowed:
#      - [0, 24]
#      - [0,6]  # EURGBP
#      - [17,24]  # EURGBP
      - [0, 11]  # EURUSD
      - [16, 24]  # EURUSD
    allowed_days:
#      [0, 1, 2, 3, 4, 5, 6]  # EURGBP
      [0, 1, 4]  # Только будни: Пн, Вт, Пт   # EURUSD

output:
  destination_path: "outputs/backtest_outputs"
  stats_results: true